### ISSUE TITLE
[Server Health Monitor] [ifstat] invalid option

### ISSUE THREAD

**Issue by laegnur** [alexloehner/lico-bash-collection#1]
Hello.

In the Description of the Server Health Monitor script, you said we need to add to the rc.local file the command:

/usr/bin/ifstat -n -z -q -b -i em1 2 >/tmp/netstat.log 2>/dev/null &

When I tried to execute this command, I have this result:

/usr/bin/ifstat: invalid option -- 'q'
Usage: ifstat [OPTION] [ PATTERN [ PATTERN ] ]
   -h, --help		this message
   -a, --ignore	ignore history
   -d, --scan=SECS	sample every statistics every SECS
   -e, --errors	show errors
   -j, --json          format output in JSON
   -n, --nooutput	do history only
   -r, --reset		reset history
   -s, --noupdate	don't update history
   -t, --interval=SECS	report average over the last SECS
   -V, --version	output version information
   -z, --zeros		show entries with zero activity

Could you say what meaning have the options you use?

**Comment by alexloehner** [comment]
Hey @laegnur , which version of ifstat are you using there? 
Mine is this:

    $ ifstat -v
    ifstat version 1.1.
    Copyright (C) 2001-2003, Ga▒l Roualland <gael.roualland@dial.oleane.com>
    Compiled-in drivers: proc, snmp.

the putput of your ifstat should be something like this:

           em1
     Kbps in  Kbps out
       25.15    180.85
       28.24    167.93
       18.28     11.80
       52.34    102.38
       58.50    337.44

The monitoring bash script always gets the last line of the output to get the most up to date traffic.

I guess you can archive nearly the same output with this command line:

    $ /usr/bin/ifstat -n

But it seems that your version outputs KB/s (kilobytes) only, not kb/s (kilobits). So you also may want to adjust the output of the unit in the bash script.

**Comment by laegnur** [comment]
Hello

I'm usign Arch Linux, and this is what this command said to me:

$ /sr/bin/ifstat -v
ifstat utility, iproute2-ss150706

**Comment by skynet** [comment]
Same problem  here:
```
$ ifstat -i eth0 -b -n
ifstat: invalid option -- 'i'
```
